### ISSUE TITLE
VS Code dart linter error

### ISSUE THREAD

**Issue by LRNZ09** [fluttercommunity/flutter_after_layout#1]
Hi, I'm happily using this library but I have an error using it with Visual Studio Code.
In fact, it's telling me this:

> [dart] The class 'AfterLayoutMixin' can't be used as a mixin because it extends a class other than Object.
`abstract class AfterLayoutMixin<T extends StatefulWidget> extends State<T>`

Except this, I have no problems compiling the app.

**Comment by ianrothmann** [comment]
Create a file called analysis_options.yaml next to pubspec.yaml.

```
analyzer:
  language:
    enableSuperMixins: true
```

Should do the trick.

**Comment by LRNZ09** [comment]
It worked, thanks a lot!
