### ISSUE TITLE
Why pass context? 

### ISSUE THREAD

**Issue by Cretezy** [fluttercommunity/flutter_after_layout#11]
Why does the callback accept a context, when context available at the widget scope and is equivalent to the argument?

**Comment by codewhen** [comment]
The context can be optional too. But in code it was not done that way. It is only there if you need to perform a function which needs context. Then only the passed context argument is needed.
Maintainer can assign me if they want to make the context argument optional.

**Comment by maheshj01** [comment]
I am just curious, how does this flutter After layout plugin beneficial compared to the built in [ SchedularBinding](https://api.flutter.dev/flutter/scheduler/SchedulerBinding/endOfFrame.html)

**Comment by codewhen** [comment]
> I am just curious, how does this flutter After layout plugin beneficial compared to the built in [ SchedularBinding](https://api.flutter.dev/flutter/scheduler/SchedulerBinding/endOfFrame.html)

This plugin is actually using widgetBinding to my knowledge.

**Comment by esDotDev** [comment]
Ya, it's literally just a `addPostFrameCallback` under the hood:
`WidgetsBinding.instance!.addPostFrameCallback((_) => afterFirstLayout(context));`

Fwiw, scheduleMicrotask will also do it: 
```
void initState() {
  super.initState();
  scheduleMicrotask(() => showDialog(context: context, builder: ...));
}
```

**Comment by slightfoot** [comment]
It was a design artefact that helps people more code between build methods and StatelessWidgets into the callback. There is no harm in having it given as a parameter so I would rather leave it in and not break backwards compatibility.
Re other question: see #22
