### ISSUE TITLE
I want to wait for some data to load before i show the dialog

### ISSUE THREAD

**Issue by Emmanuelfrimpong** [fluttercommunity/flutter_after_layout#13]
in my project i get data from database on initialization, and i want to show dialog after the data is fetched .
can this library help me? the dialog pop up even before the data is fetched.

**Comment by mvarendorff** [comment]
Use a Future to fetch your date in the function and `then` to show the dialog when it's competed

**Comment by maheshj01** [comment]
> in my project i get data from database on initialization, and i want to show dialog after the data is fetched .
> can this library help me? the dialog pop up even before the data is fetched.

Make sure you ```await``` while you access the database.
You could paste the code for a more precise answer. Also, I believe this is not the right place to ask How to questions :)

**Comment by slightfoot** [comment]
You can now override afterFirstLayout as a Future as of v1.2.0. Just remember to call `if(mounted)` before you try and use your context.
