### ISSUE TITLE
after_layout VS addPostFrameCallback

### ISSUE THREAD

**Issue by mellowcello77** [fluttercommunity/flutter_after_layout#22]
Please help me understand the difference between this package and using WidgetsBinding.instance!.addPostFrameCallback in initState. A call back works fine for me, I just don't know if I am missing something? Thanks

**Comment by tomwyr** [comment]
This is literally what the packages does:
https://github.com/fluttercommunity/flutter_after_layout/blob/master/lib/after_layout.dart#L9

**Comment by Andreigr0** [comment]
So it's just a duplication. What for does it exist?

**Comment by slightfoot** [comment]
It's just to add a nice callback function to make it standard across your app. Also addPostFrameCallback was not known or understood by many people when we made this. So they felt it was nicer to have a package.

**Comment by toknT** [comment]
> This is literally what the packages does: https://github.com/fluttercommunity/flutter_after_layout/blob/master/lib/after_layout.dart#L9

I am new comer , and can't find any code about how to use `WidgetsBinding` until meet your comment.
