### ISSUE TITLE
Hi,see SchedulerBinding.instance.endOfFrame,it's more simple

### ISSUE THREAD

**Issue by fantasy525** [fluttercommunity/flutter_after_layout#8]
Hi,I try this:
```javascript

SchedulerBinding.instance.endOfFrame.then((value){
        showDialog(
          context: context,
          builder: (context){
            return Text('hello');
          }
        );
      });
```
it can work nice!.

**Comment by devilishWei** [comment]
works for me, thanks

**Comment by alyyasser** [comment]
> Hi,I try this:
> 
> 
> ```js
> SchedulerBinding.instance.endOfFrame.then((value){
>         showDialog(
>           context: context,
>           builder: (context){
>             return Text('hello');
>           }
>         );
>       });
> ```
> 
> it can work nice!.

is there any explanation on why it's simpler? what's the difference between your example with current `after_layout` implementation?

**Comment by fantasy525** [comment]
> > Hi,I try this:
> > ```js
> > SchedulerBinding.instance.endOfFrame.then((value){
> >         showDialog(
> >           context: context,
> >           builder: (context){
> >             return Text('hello');
> >           }
> >         );
> >       });
> > ```
> > 
> > 
> > it can work nice!.
> 
> is there any explanation on why it's simpler? what's the difference between your example with current `after_layout` implementation?

I just think it's no need to install a third party dependency.
Fluttter has provided a very simple API.
```
WidgetsBinding.instance
        .addPostFrameCallback((_) => afterFirstLayout(context));
```
and 

```
SchedulerBinding.instance.endOfFrame.then((_) => fn());
```
They have the same effect.
```
mixin WidgetsBinding on BindingBase, SchedulerBinding
```
